- getting-started/custom-configuration.md
I added an explanation about `exclude.branches` option because the option had been available several weeks ago...
> Add document about `exclude.branches`

- tools/swift/swiftlint.md
Sider runs Swift 4.2.1.
See https://github.com/sider/devon_rex_swift/pull/4
> Update Swift version from 4.1.3 to 4.2.1

- tools/javascript/tslint.md
`type-check` option is already deprecated.
> Remove `type-check` option from the example

- tools/javascript/tslint.md
We now allow using `rules-dir` option as an array when analyzing TSLint.
>  Allow to set array for `rules-dir` option

- docs/enterprise/quick-start/setup.md
- docs/enterprise/quick-start/update.md
- docs/enterprise/releases/changelog.md
- docs/enterprise/resources.md
- docs/enterprise/testing/guide.md
- website/_redirects
- website/static/css/custom.css
After changing document platform, `/on-premises` contents were broken. Hence, I fix this to set redirect.
See https://www.netlify.com/docs/redirects 
If this redirect were failed, I'd try that redirection with our Rack application.
> Fix enterprise docs path

- docs/tools/ruby/rubocop.md
Sider now supports third-party RubyGems repository and Git repository.
> Flexible gem installation support for RuboCop

- docs/enterprise/releases/changelog.md
Changes from the previous release:
* [sideci](https://github.com/sider/sideci/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-01-10..2019-02-14+-label%3Adependencies)
* [catpost](https://github.com/sider/catpost/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-01-10..2019-02-14+-label%3Adependencies)
* [setaria](https://github.com/sider/setaria/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-01-10..2019-02-14+-label%3Adependencies)
> Enterprise Release on February 2019

- docs/enterprise/config.md
`STATUS_PAGE_URL` and `DOCS_PAGE_URL` are not required for Sider Enterprise.
> Remove unnecessary environment variables

- docs/getting-started/working-with-issues.md
Follow up of https://blog.sideci.com/restricting-access-to-close-button-b0d3e0c12346
> Follow up of close restrictions in working with issues

- docs/enterprise/containers.md
- docs/enterprise/outline.md
We need to run [resque-scheduler](https://github.com/resque/resque-scheduler) for delayed retry of catpost jobs.
> Add note about resque-scheduler

- website/siteConfig.js
See https://docusaurus.io/docs/en/site-config#gatrackingid-string
> Add `gaTrackingId`

- docs/index.md
I received opinions about `<details>`, which should be opened initially. So I added `open` to `<details>`.
> Keep `<deatails>` open

- docs/enterprise/releases/changelog.md
See #117 
`resque:scheduler` is still required.
> Revise release - catpost resuqe:scheduler is still required

- docs/enterprise/resources.md
The capacity planning for Sider Enterprise clearly requires the number of analyses (commits), and this is it.
The # of analyses are based on the SaaS version. We know the number is insufficient to help your planning for Sider Enterprise, but we believe having this number is better than nothing.
> Add # of analyses on resources.md

- docs/getting-started/custom-configuration.md
- docs/tools/css/scss-lint.md
- docs/tools/css/stylelint.md
- docs/tools/go/gometalinter.md
- docs/tools/java/checkstyle.md
- docs/tools/java/pmd.md
- docs/tools/javascript/coffeelint.md
- docs/tools/javascript/eslint.md
- docs/tools/javascript/jshint.md
- docs/tools/javascript/tslint.md
- docs/tools/others/goodcheck.md
- docs/tools/others/misspell.md
- docs/tools/php/codesniffer.md
- docs/tools/php/phinder.md
- docs/tools/php/phpmd.md
- docs/tools/python/flake8.md
- docs/tools/ruby/brakeman.md
- docs/tools/ruby/haml-lint.md
- docs/tools/ruby/querly.md
- docs/tools/ruby/rails-bestpractices.md
- docs/tools/ruby/reek.md
- docs/tools/ruby/rubocop.md
- docs/tools/swift/swiftlint.md
https://help.sider.review/getting-started/custom-configuration#configuration-via-sideciyml
https://help.sider.review/getting-started/custom-configuration#branches-option
https://deploy-preview-145--sider-docs.netlify.com/getting-started/custom-configuration#configuration-via-sideciyml
https://deploy-preview-145--sider-docs.netlify.com/getting-started/custom-configuration#branches-option
Highlight.js doesn't support a class name with a filename... 😓
> Fix broken syntax highlight for `sideci.yml` code

- docs/advanced-settings/private-dependencies.md
We've heard that some users aren't sure which repository they should configure with an SSH public key after downloading it. To make it clear, I added a description.
> Add a description of SSH Key

- docs/custom-rules/tips.md
- website/sidebars.json
Add a document to explain:
* How to share rules among repositories.
* A set of hints to help users finding their rules.
> Add custom rules tips page

- docs/getting-started/permissions.md
We added a feature that organization owners can invite their members to Sider. Thus I add the required permission to use the feature.
> Add invitation member required permission

- website/core/Footer.js
- website/core/plugins/Inspectlet.js
- website/package.json
- website/siteConfig.js
- website/yarn.lock
Introduce Inspectlet but it's workaround.
Inspectlet documents said:
> The script provided by Inspectlet (look above for an example) should be placed anywhere in your site's HTML (preferrably in the <HEAD> section).
Because Docusaurus 1.x(and its latest version, 2.0.0-alpha16, is too) doesn't seem to allow users to edit `<head>` tag, I added Inspectlet tag to under `<footer>` tag, which is the only tag to editable today.
If Docusaurus 2.x relax edit limitation to users, I would like to introduce Google Tag Manager and move GA and Instpectlet to GTM.
> Introduce inspectlet

- docs/tools/others/goodcheck.md
We now use Goodcheck 1.7.1 to default.
> Use Goodcheck 1.7.1

- website/yarn.lock
- yarn.lock
GitHub has alerted that packages' vulnerability, therefore upgraded packages version.
I upgraded all packages without careful consideration because sider-docs is almost static pages application and must have shallow dependencies on each package.
> yarn upgrade to calm security alert

- website/yarn.lock
under.score package had valnerability:
https://github.com/epeli/underscore.string/issues/510
Therefore, I upgraded the package together with other packages by `yarn upgrade`.
There will be tolerable execution since we have 8 days after running `yarn upgrade` and almost upgraded packages were minor updates.
> Calm security alert

- docs/index.md
Hi!
JSHint and TSLint links in the doc seem to be wrong.
This PR fixes that.
> Fix the wrong links for JSHint and TSLint

- docs/getting-started/custom-configuration.md
- docs/tools/css/scss-lint.md
- docs/tools/css/stylelint.md
- docs/tools/go/gometalinter.md
- docs/tools/java/checkstyle.md
- docs/tools/java/pmd.md
- docs/tools/javascript/coffeelint.md
- docs/tools/javascript/eslint.md
- docs/tools/javascript/jshint.md
- docs/tools/javascript/tslint.md
- docs/tools/others/goodcheck.md
- docs/tools/others/misspell.md
- docs/tools/php/codesniffer.md
- docs/tools/php/phinder.md
- docs/tools/php/phpmd.md
- docs/tools/python/flake8.md
- docs/tools/ruby/brakeman.md
- docs/tools/ruby/haml-lint.md
- docs/tools/ruby/querly.md
- docs/tools/ruby/rails-bestpractices.md
- docs/tools/ruby/reek.md
- docs/tools/ruby/rubocop.md
- docs/tools/swift/swiftlint.md
- docs/troubleshooting.md
- goodcheck.yml
Renamed `sideci.yml` to `sider.yml`.
For the backward compatibility, `sideci.yml` is still supported. But Sider recognizes `sider.yml` if `sider.yml` and `sideci.yml` both exist.
> Sider now recognizes `sider.yml`

- docs/tools/ruby/rubocop.md
`--rails` option was removed in RuboCop v0.72.0. See https://github.com/rubocop-hq/rubocop/pull/7095
Sider already has been ignored the option if a user is using RuboCop v0.72.0 or later. This PR updates documentation to describe the behavior.
> Add note about `--rails` option after v0.72.0

- docs/tools/javascript/coffeelint.md
The homepage URL <http://www.coffeelint.org/> has been down, so this changes it to the GitHub repository URL.
Related issue: https://github.com/clutchski/coffeelint/issues/643
> Fix CoffeeLint homepage URL

- docs/tools/go/gometalinter.md
- docs/tools/javascript/eslint.md
- docs/tools/javascript/jshint.md
- docs/tools/php/phpmd.md
- docs/tools/python/flake8.md
We have https://github.com/actcat/sideci_config as our service's default configuration settings.
However, it is too old to run on our documents because the settings were published for our ancient systems.
Thus, I specify default settings not but sideci_config URL.
> Specify default configuration instead of sideci_config

- docs/tools/php/codesniffer.md
We no longer support PHP_CodeSniffer version 2, thus I'd like to update document about `version` option of the tool.
> Update document about `version` option

- docs/enterprise/github.md
GitHub Enterprise users have to set "Email" `Read-only` on the "User permissions" section.
> Add "User permissions" section for GHE

- docs/getting-started/custom-configuration.md
- docs/index.md
- docs/tools/css/stylelint.md
- docs/tools/javascript/coffeelint.md
- docs/tools/javascript/eslint.md
- docs/tools/javascript/tslint.md
- website/sidebars.json
Especially for [the release on August 20](https://blog.sideci.com/new-release-about-yarn-support-40123d5f9d84).
- Shallow heading levels for each option of analyzers. Deeper levels make it difficult for us to understand a document structure rapidly.
- Simplify some verbose description, and add some links to the official documentation of analyzers.
- Format markdown files in this PR via **Prettier**, so this PR has many diffs.
- Move the CSS category right next to the JavaScript category. They are relevant to each other.
> Update description about npm analyzers

- docs/tools/javascript/tyscan.md
- Split "Language" and "Runtime" items.
- Fix a broken YAML example.
> Fix TyScan page

- docs/advanced-settings/private-dependencies.md
- "A" -> "my-app"
- "B" -> "my-lib"
> Make repository example names more understandable

- docs/tools/css/scss-lint.md
SCSS-Lint will stop its updates in the nearly future.
https://github.com/sds/scss-lint#notice-consider-other-tools-before-adopting-scss-lint
> Deprecate SCSS-Lint

- docs/tools/css/scss-lint.md
These versions are not very important and hard to maintain.
> Drop Sass and Ruby versions on SCSS-Lint page

- docs/tools/css/stylelint.md
- docs/tools/go/golint.md
- docs/tools/go/gometalinter.md
- docs/tools/go/govet.md
- docs/tools/java/checkstyle.md
- docs/tools/java/pmd.md
- docs/tools/javascript/eslint.md
- docs/tools/javascript/tslint.md
- docs/tools/javascript/tyscan.md
- docs/tools/php/codesniffer.md
- docs/tools/php/phinder.md
- docs/tools/php/phpmd.md
- docs/tools/python/flake8.md
- docs/tools/ruby/haml-lint.md
- docs/tools/ruby/rubocop.md
- Language
- Go: 1.12.7 -> 1.13.1
- PHP: 7.3.9 -> 7.3.10
- Tool
- Checkstyle: 8.23 -> 8.25
- ESLint: 5.16.0 -> 6.5.1
- Flake8: 3.7.7 -> 3.7.8
- HAML-Lint: 0.32.0 -> 0.33.0
- PMD Java: 6.17.0 -> 6.18.0
- RuboCop: 0.74.0 -> 0.75.0
- stylelint: 10.1.0 -> 11.0.0
- TSLint: 5.18.0 -> 5.20.0
- TyScan: 0.2.1 -> 0.3.1
- https://github.com/sider/runners/blob/master/CHANGELOG.md#040
- https://github.com/sider/devon_rex/blob/master/CHANGELOG.md#230
> Update tools' default versions and language versions

- docs/tools/shellscript/shellcheck.md
The `target` option can receive only files (not directories).
> Fix ShellCheck configuration example

- docs/enterprise/healthcheck.md
For Sider Enterprise, users sometimes have to configure the load balancer to set the `X-Forwarded-For` HTTP header.
> Add a description about X-Forwarded-For HTTP header

- docs/tools/python/flake8.md
Python 2 will be retired soon.
https://www.python.org/psf/press-release/pr20191220/
> Add deprecated mark on Flake8 page

- docs/tools/php/codesniffer.md
> Fix wrong `sider.yml` sample for PHP_CodeSniffer

- docs/news/2020.md
- docs/tools/ruby/rubocop.md
See <https://github.com/sider/runners/blob/master/CHANGELOG.md#0200>.
> [News] Update the default version of RuboCop to 0.80.0

- docs/tools/go/golangci-lint.md
Follow up #290 
- Fix `id` to show the sidebar.
- Fix Go version.
- Add warning: "This is **not published yet**"
- Add a link to the Sider default configuration (sider/runners).
- Fix heading levels.
- Remove too detailed descriptions because we will be hard to maintain.
> Improve GolangCI-Lint document

- docs/tools/go/golangci-lint.md
Because of sider/runners#779, the field name has changed.
> Change YAML field name of GolangCI-Lint

- docs/tools/csharp/fxcop.md
Now, the URL is https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysisfxcopanalyzers. It may be broken because it is a pointer to README.md in a github repo.
This commit change the url to permanent one.
> Change FxCop Analyzer homepage URL

- docs/index.md
- docs/tools/cplusplus/cppcheck.md
- docs/tools/cplusplus/cpplint.md
- docs/tools/csharp/fxcop.md
- docs/tools/css/scss-lint.md
- docs/tools/dockerfile/hadolint.md
- docs/tools/go/golangci-lint.md
- docs/tools/go/golint.md
- docs/tools/go/gometalinter.md
- docs/tools/go/govet.md
- docs/tools/javascript/tslint.md
- docs/tools/kotlin/detekt.md
- docs/tools/kotlin/ktlint.md
- docs/tools/python/flake8.md
- website/sidebars.json
- Remove `<details>` on the homepage.
- Fix the number of supported tools and languages.
- Add `(deprecated)` and `(beta)` tags on the left sidebar labels.
- Fix "not published". Fix #306 
- Make deprecations' position consistent.
> Improve documents for deprecations and betas

- .remarkrc.yml
- package.json
- Move the remark-lint configuration from `package.json` to `.remarkrc.yml`
- Change the rules' severity to `error` except for `remark-lint-no-dead-urls`
- Keep the severity of `remark-lint-no-dead-urls` as `warning`
- Because GitHub often returns "429 too many requests" error
- Trim the `--frail` option of the `remark` command. This doesn't exit with 1 even if warnings are detected
Close #330
> Reconfigure remark-lint

- docs/tools/php/phpmd.md
- Make it simple redundant wordings.
- Fix some typos.
- Fix some mistakes.
- Change the default configuration code block to a link.
> Some improvements for the PHPMD document

- docs/tools/php/codesniffer.md
The option will be deprecated. See <https://github.com/sider/runners/pull/878>.
> Remove PHP_CodeSniffer `version` option

- docs/getting-started/custom-configuration.md
Sometimes, `npm_install: false` is necessary, so I added about the reason.
> Update the explanation of npm_install

- website/yarn.lock
This change can fix vulnerable dependencies.
```console
$ yarn audit
yarn audit v1.22.4
0 vulnerabilities found - Packages audited: 11076
Done in 1.48s.
```
> Bump dependencies via `yarn upgrade`

- docs/tools/go/golangci-lint.md
govet and golint has been deprecated, so I think this new description should be useful for existing users.
> Add description about migration from govet and golint

- docs/enterprise/releases/202004.md
From the release `release-202004.0`, I want to add the Runners version in the "Features" section.
> Add Runners version on the release notes

- docs/tools/cplusplus/cppcheck.md
- Replace sourceforge.net with github.com for the website. Because the former is often down.
- Clarify the each option's description.
> [Cppcheck] Improve document

- docs/tools/ruby/haml-lint.md
- Add a brief description of HAML-Lint.
- Add each option's description.
> [HAML-Lint] Improve document

- docs/tools/java/checkstyle.md
- Add a brief summary about Checkstyle.
- Fix the domain `sourceforge.net` in links to `checkstyle.org`.
> [Checkstyle] Improve document

- docs/tools/python/flake8.md
- Add a brief summary for the tool.
- Replace the code snippet for the default configuration with just the link.
> [Flake8] Improve document

- docs/tools/css/stylelint.md
- Replace the default configuration snippet with just a link.
> [stylelint] Improve document

- docs/tools/go/golangci-lint.md
- Fix the links for the new website (https://golangci-lint.run).
- Add a description about `.golangci.yml`.
- Add a description about the Govet or Golint users.
> [GolangCI-Lint] Some improvements

- docs/getting-started/custom-configuration.md
- docs/tools/go/golint.md
- docs/tools/go/govet.md
It seems hard for users to configure `sider.yml` (e.g. typos of `govet` and `go_vet`).
So, this change aims to help uses understand how to configure and fix `sider.yml`.
This also adds the missing options tables for Golint and Govet.
> Add description about `linter.*` options of `sider.yml`

- docs/enterprise/config.md
Sider Enterprise requires environment variables before executing any Rails tasks, so I replaced the example command.
```console
$ python -c 'import secrets; print(secrets.token_hex(64))'
db80c184fa1899d795f38b44af3842b255d74a7802f0e6ef5009e7c78960e3c8679515f000858e52df88d44d817e705273f1b1c3b1c96a7911698b78b699ceb0
$ ruby -r securerandom -e 'puts(SecureRandom.hex(64))'
7f501e215c1727a6ae78c4e06beca74032f512e969224d3ce503a99abcd7188a9e4a92a6967a379c13c95c0c56bc38e2a9daa0121c1a9a5849d11b9baecc5fc4
```
> Do not use `rails secret`

- docs/enterprise/config.md
- docs/enterprise/github.md
- docs/tools/cplusplus/cppcheck.md
- docs/tools/markdown/remark-lint.md
- The default branches were changed from `master` to `main`.
- developer.github.com was unified to docs.github.com (actually deprecated still, not dead)
See https://github.blog/2020-07-01-launching-docs-github-com/
> Fix dead URLs

- docs/tools/ruby/querly.md
`querly.yaml` ➡️ `querly.yml`
See https://github.com/soutaro/querly#quick-start
> [Querly] Fix default config file name

- docs/enterprise/operation.md
`RESTRICT_SIGN_UP` requires administrators to create users manually, but this explanation lacked on our document.
> Add "Register users on Sider manually"

- docs/enterprise/installation.md
Proxy environments need to pass proxy information to `docker run`.
> Add a note for proxy environments

- docs/tools/others/misspell.md
https://github.com/sider/runners/blob/0.36.1/lib/runners/processor/misspell.rb#L8
> [Misspell] Allow `string` type for `target` option

- website/yarn.lock
- yarn.lock
Bump all packages via the `yarn upgrade` command:
```console
$ yarn upgrade
$ cd website && yarn upgrade
```
As a result, `yarn audit` outputs `0 vulnerabilities found`.
> yarn upgrade

- docs/enterprise/config.md
- docs/enterprise/examples/single-node-with-docker-compose.md
- docs/enterprise/installation.md
- docs/enterprise/mysql.md
This change mainly removes the needless query parameters of the MySQL connection URL (`DATABASE_URL`).
- `encoding=utf8mb4` - it's automatically set by default
- `connectTimeout=5000` - it's an invalid parameter (just ignored)
See the [`mysql2`](https://github.com/brianmario/mysql2) document for more details about the URL format and available parameters.
Also, this change unifies the pages to describe the URL.
> Fix MySQL connection URL

- docs/tools/python/flake8.md
- docs/tools/python/pylint.md
Following https://github.com/sider/devon_rex/pull/307 and https://github.com/sider/runners/pull/1579, I want to update the documentation.
Note I kept the version of Flake8 and PyLint deliberately. If I should update these versions, please comment here.
> Drop the support of Python 2

- docs/advanced-settings/private-dependencies.md
- docs/troubleshooting.md
Summary:
- Add a section about a machine user
- Clarify the existing descriptions
- Also add a section about private dependencies to the "Troubleshooting" page
See also <https://docs.github.com/en/free-pro-team@latest/developers/overview/managing-deploy-keys>
> Rewrite "Private Dependencies" page

- docs/enterprise/releases/202012.md
- docs/enterprise/system-overview.md
With [Analyzing branches](https://help.sider.review//news/2020#analyzing-branches), Sider Enterprise might require more storage size, so I updated the least storage size from `100` to `500`.
Note this number is not what is exactly calculated, but it's good to prepare more storage size for Sider Enterprise.
> Increase the recommended storage size on System Overview

- docs/getting-started/custom-configuration.md
This change aims to promote users renaming `sideci.yml` to `sider.yml`.
> Improve warning message about `sideci.yml`

- website/.eslintrc.yml
Follow-up of #544
See also <https://eslint.org/docs/user-guide/configuring#specifying-parser-options>
> Add `sourceType` and `env` to ESLint config

- docs/index.md
TSLint and SCSS-Lint are deprecated.
> Remove deprecated tools from home

- docs/tools/csharp/fxcop.md
We have implemented the analyzer for FxCop based on **Roslyn Analyzers**.
See also <https://github.com/sider/roslyn-analyzers-runner>.
> Fix FxCop website URL

- docs/tools/cplusplus/cppcheck.md
This change makes the order of the options in the `sider.yml` example the same as one in the **options** table.
> [Cppcheck] Sort options in `sider.yml` example

- docs/index.md
- docs/news/2021.md
- docs/tools/dockerfile/hadolint.md
- docs/tools/ruby/haml-lint.md
- docs/tools/ruby/slim-lint.md
- website/sidebars.json
The document structure is similar to the HAML-Lint's one:
https://github.com/sider/sider-docs/blob/slim-lint/docs/tools/ruby/haml-lint.md
See also <https://github.com/sider/runners/pull/2014>.
> [News] 2021-02-12

- docs/tools/go/golangci-lint.md
- docs/tools/go/golint.md
- docs/tools/go/gometalinter.md
- docs/tools/go/govet.md
Govet, Golint, and GoMetaLinter has been removed already, so *deprecated* is inaccurate.
> Make more accurate description about removed Go tools

- docs/tools/ruby/reek.md
`.reek.yml` is a default configuration file name of Reek. I think it useful to describe this file name in our documentation.
See <https://github.com/troessner/reek#configuration-file>.
> [Reek] Add description about `.reek.yml`

- docs/tools/ruby/rubocop.md
See <https://github.com/rubocop/rubocop/discussions/9517> for details.
> Rename RuboCop organization: rubocop-hq -> rubocop

- docs/tools/java/checkstyle.md
- Use `HEAD` for GitHub links.
- More accurate description about a custom *path*.
> [Checkstyle] Improve `config` option

- .remarkrc.yml
> Typically, you don’t need to configure remark-validate-links, as it detects local Git repositories. 
https://github.com/remarkjs/remark-validate-links/blob/10.0.4/readme.md#configuration
> Simplify remark-validate-links configuration

- docs/tools/python/flake8.md
`flake8-bandit` seems inactive. Instead, this change uses `flake8-bugbear`.
See also:
- https://github.com/PyCQA/flake8-bugbear
- https://github.com/tylerwince/flake8-bandit
> [Flake8] Change plugin example

- docs/enterprise/releases/202101.md
Sider can't work with GitHub Enterprise Server before version `2.22`. Add a caution message to the release notes for Jan 2021 release.
> [Enterprise] Add requirement information (Jan 2021 release)

- docs/index.md
- docs/news/2021.md
- docs/tools/css/stylelint.md
- docs/tools/dockerfile/hadolint.md
- docs/tools/go/golangci-lint.md
- docs/tools/java/checkstyle.md
- docs/tools/java/pmd.md
- docs/tools/javascript/coffeelint.md
- docs/tools/javascript/eslint.md
- docs/tools/others/pmd-cpd.md
- docs/tools/php/code-sniffer.md
- docs/tools/php/phpmd.md
- docs/tools/python/flake8.md
- docs/tools/python/pylint.md
- docs/tools/ruby/brakeman.md
- docs/tools/ruby/rails-best-practices.md
- docs/tools/ruby/reek.md
- docs/tools/ruby/rubocop.md
- docs/tools/shellscript/shellcheck.md
https://github.com/sider/runners/blob/0.48.0/CHANGELOG.md
- Include Runners 0.48.0
- Update tools
- Deprecate Rails Best Practices
> [News] 2021-05-xx

- docs/tools/dockerfile/hadolint.md
`hadolint` does not allow directories as arguments:
- https://github.com/sider/runners/blob/c31bbdfe2004869dbea294b9582671a568c4cb4b/lib/runners/processor/hadolint.rb#L45
- https://github.com/sider/runners/blob/c31bbdfe2004869dbea294b9582671a568c4cb4b/lib/runners/processor/hadolint.rb#L68-L79
> [hadolint] Fix inaccurate description about `targer` option
