sider/sider-docs

tools/php/phinder.md, tools/python/flake8.md, tools/ruby/haml-lint.md, tools/swift/swiftlint.md
This is document update to follow runners' updates, which are introducing schema checking.
=> Update docs schema check

on-premises/releases/README.md
Changes from the previous release:
* sideci
- https://github.com/sider/sideci/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+created%3A2018-11-12..2018-12-10+-label%3Adependencies+
* catpost
-  https://github.com/sider/catpost/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+created%3A2018-11-12..2018-12-10+-label%3Adependencies+
* setaria
-  https://github.com/sider/setaria/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+created%3A2018-11-12..2018-12-10+-label%3Adependencies+
=> Release Sider Enterprise of Dec. 2018

SUMMARY.md, getting-started/README.md, getting-started/permissions.md
I'd like to add permission tables to use Sider.
=> Add permissions table to use Sider

tools/java/checkstyle.md, tools/java/pmd.md, tools/javascript/jshint.md, tools/php/phinder.md, tools/swift/swiftlint.md
We've updated analysis tools 🎅
=> Tools update in December :snowman:

SUMMARY.md
=> Revert "Add ToC"

tools/javascript/coffeelint.md, tools/javascript/eslint.md, tools/javascript/jshint.md, tools/javascript/tslint.md
We've updated Node.js version which Sider uses, so follow up that update.
https://github.com/sider/devon_rex_npm/pull/7
=> Follow Node.js version update

README.md, SUMMARY.md, on-premises/README.md
I finally concluded that changing URLs cannot be implemented using GitBook. 🙄
=> Just content update

on-premises/quick-start/setup.md, on-premises/releases/README.md
Add a release note and some changes about Enterprise release on **January 2019**.
=> Enterprise Release on January 2019

docs/tools/ruby/querly.md
https://help.sider.review/tools/ruby/querly
=> Capitalize Querly

docs/billing-and-plans.md, docs/enterprise/quick-start/setup.md, docs/introduction.md, docs/troubleshooting.md
`yarn run lint`
```
README.md: no issues found
docs/advanced-settings/inline-comments.md: no issues found
docs/advanced-settings/private-dependencies.md: no issues found
docs/billing-and-plans.md: no issues found
docs/enterprise/quick-start/setup.md: no issues found
docs/enterprise/quick-start/update.md: no issues found
docs/enterprise/releases/changelog.md: no issues found
docs/enterprise/resources.md: no issues found
docs/enterprise/testing/guide.md: no issues found
docs/getting-started/custom-configuration.md: no issues found
docs/getting-started/permissions.md: no issues found
docs/getting-started/repository-settings.md: no issues found
docs/getting-started/setup.md: no issues found
docs/getting-started/working-with-issues.md: no issues found
docs/introduction.md: no issues found …
```
=> Fix links via lint

website/siteConfig.js
See [documentation](https://docusaurus.io/docs/en/site-config#editurl-string).
=> Add "Edit" button

website/siteConfig.js, website/static/css/custom.css
We finally introduce Algolia into our documentation 🎉
=> Add search feature

docs/tools/css/stylelint.md, docs/tools/go/golint.md, docs/tools/go/govet.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/python/flake8.md, docs/tools/ruby/querly.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
Update items as follows:
* Tools version.
* Specify support version for NPM tools.
https://3.basecamp.com/3787557/buckets/4301431/todolists/1600524174
=> Tools Update on 2019 Feb.

docs/index.md
=> Fix typo: 7 -> 6

docs/getting-started/custom-configuration.md
See https://github.com/sider/sideci/pull/4343
=> Add example about regexp exclude pattern

docs/enterprise/releases/changelog.md
Changes from the previous release:
* [sideci](https://github.com/sider/sideci/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-02-14..2019-03-12+-label%3Adependencies)
* [catpost](https://github.com/sider/catpost/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-02-14..2019-03-12+-label%3Adependencies)
* [setaria](https://github.com/sider/setaria/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-02-14..2019-03-12+-label%3Adependencies)
* [configure](https://github.com/sider/configure/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-02-14..2019-03-12+-label%3Adependencies)
* [enterprise-config](https://github.com/sider/enterprise-config/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-02-14..2019-03-12+-label%3Adependencies)
=> Enterprise Release on March 2019

docs/advanced-settings/transferring-a-repository.md
See comments below:
* https://github.com/sider/sider-docs/pull/122#discussion_r264563278
* https://github.com/sider/sider-docs/pull/122#discussion_r264564344
Thanks, @ivanha09
=> Fix sentences on transferring-a-repository

docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/others/goodcheck.md, docs/tools/php/phinder.md, docs/tools/python/flake8.md, docs/tools/ruby/querly.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
We updated the tools' version.
=> Update tool versions March 2019

docs/advanced-settings/private-dependencies.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/querly.md
`gems` option is now available in Querly and Brakeman.
=> Update Querly and Brakeman docs

website/static/css/custom.css
=> Fix search CSS

docs/advanced-settings/private-dependencies.md, docs/tools/others/goodcheck.md, docs/tools/ruby/haml-lint.md
The `gem` option is now available in Goodcheck and HAML-Lint
=> Update goodcheck and haml-lint docs

docs/enterprise/healthcheck.md, website/sidebars.json
Add document about health check.
=> Add healthcheck guide

docs/custom-rules/goodcheck.md, docs/custom-tools/goodcheck.md, docs/tools/others/goodcheck.md, docs/tools/php/phinder.md, docs/tools/ruby/querly.md, website/sidebars.json
This section is to help users with custom rules and goodcheck by providing examples of rules and basic instructions.
=> Custom rules / goodcheck

docs/tools/others/goodcheck.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/querly.md, docs/tools/ruby/rails-bestpractices.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md
See https://github.com/sider/sider-docs/pull/139#discussion_r269870167
=> Documentation tweaks

.circleci/config.yml, docs/tools/others/goodcheck.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/querly.md, docs/tools/ruby/rails-bestpractices.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, website/package.json, website/yarn.lock
See:
- https://github.com/sider/sider-docs/pull/134#discussion_r268517057
- https://github.com/facebook/Docusaurus/pull/1309
- https://github.com/facebook/Docusaurus/releases/tag/v1.8.0
- https://github.com/facebook/Docusaurus/blob/v1.8.0/CHANGELOG.md#180---2019-3-30
=> Fix `root_dir` anchor via Docusaurus 1.8.0

docs/custom-rules/goodcheck.md
Just fix indentations and trailing whitespaces.
=> Reformat YAML code snippet for `goodcheck.yml`

docs/enterprise/config.md
Also, make configurations related to Pusher optional.
Note that the change of this PR has many lines because of the deletion of trailing white spaces. You can focus on important changes with "Hide whitespace changes".
=> Add FRONTEND_POLLING_INTERVAL

docs/enterprise/releases/changelog.md
Changes from the previous release:
* [sideci](https://github.com/sider/sideci/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-03-15..2019-04-08+-label%3Adependencies)
* [catpost](https://github.com/sider/catpost/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-03-12..2019-04-08+-label%3Adependencies)
* [setaria](https://github.com/sider/setaria/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-03-12..2019-04-15+-label%3Adependencies)
* [configure](https://github.com/sider/configure/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-03-12..2019-04-08+-label%3Adependencies)
* [enterprise-config](https://github.com/sider/enterprise-config/pulls?utf8=✓&q=is%3Apr+is%3Amerged+created%3A2019-03-12..2019-04-08+-label%3Adependencies)
=> Enterprise Release on April 2019

docs/enterprise/config.md
Fix the description.
* The default value is `30`.
* Polling is enabled even if Pusher is configured.
=> Revise polling interval

docs/tools/css/stylelint.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/javascript/tslint.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md
Update default tool versions in April 2019, and a few updates.
=> Tools update in April 2019 :dango:

docs/assets/play-button.svg, docs/getting-started/intro-videos.md, docs/getting-started/setup.md, docs/getting-started/working-with-issues.md, docs/index.md, docs/tools/others/goodcheck.md, docs/tools/php/phinder.md, docs/tools/ruby/querly.md, website/sidebars.json, website/static/css/custom.css
Adding intro video section to make the videos easier to find. Also had to add some css to create a better way to display the videos in a list.
=> Add intro video and css

docs/tools/css/scss-lint.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/tslint.md, docs/tools/others/goodcheck.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/querly.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
=> Tools update in May 2019

website/core/Footer.js, website/core/plugins/Intercom.js
Add Intercom chat button into docs page.
=> Introduce Intercom chat button

website/core/Footer.js, website/core/plugins/Intercom.js
=> Revert "Revert "Introduce Intercom chat button""

docs/tools/css/stylelint.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/tslint.md, docs/tools/others/goodcheck.md, docs/tools/php/phinder.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
I followed tools update in this month.
=> Tools update in June 2019

website/siteConfig.js, website/static/css/code-block-buttons.css, website/static/js/code-block-buttons.js
I used the code from our earlier discussion on basecamp and changed the color to var(--black).
https://gist.github.com/yangshun/55db997ed0f8f4e6527571fc3bee4675
=> Add "Copy" (to Clipboard) button

docs/getting-started/custom-configuration.md
See https://github.com/sider/sider-docs/pull/179#issuecomment-507911533
=> Add note about the legacy configuration file

docs/index.md, docs/tools/java/javasee.md, docs/tools/javascript/tyscan.md, website/sidebars.json
=> Add JavaSee & TyScan document

docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/tslint.md, docs/tools/others/goodcheck.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
Monthly tools update!
In this month, we've updated 8 tools.
=> Tools update in Jul 2019

docs/tools/javascript/eslint.md
=> Fix heading levels for some ESLint options

docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/ruby/querly.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
Monthly tools update :sun_with_face:
=> Tools update in Aug 2019

netlify.toml
See <https://www.netlify.com/docs/netlify-toml-reference>
To edit the configuration file is more clear about change histories to everyone.
=> Configure netlify.toml for build

docs/tools/javascript/eslint.md
Add a note about `eslint --init` which is very useful.
=> Improve description for ESLint configuration

docs/index.md, docs/tools/cplusplus/cppcheck.md, website/sidebars.json
=> Add Cppcheck

docs/tools/css/stylelint.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md
- Node.js: 12.7.0 -> 12.10.0
- PHP: 7.3.8 -> 7.3.9
See <https://github.com/sider/devon_rex/blob/master/CHANGELOG.md#210>
=> Update runtimes: Node.js and PHP

website/yarn.lock
`yarn audit`: https://yarnpkg.com/lang/en/docs/cli/audit/
This PR aims to fix the following security issues:
=> Fix "yarn audit"

docs/tools/ruby/brakeman.md
I propose a fix typo in example yaml code 
querly -> brakeman
=> Maybe wrong typos?

docs/tools/javascript/tyscan.md
- Simplify the description about `npm install` (delegating the common description).
- Change the heading level of all options.
- Add default values to the option table.
- Simplify some descriptions.
Related to <https://github.com/sider/runners/issues/128>
=> Update TyScan document

docs/tools/kotlin/ktlint.md
Also, this adds a summary for ktlint.
=> Mark ktlint as beta

docs/getting-started/skip-analyzing.md, docs/index.md, website/sidebars.json
The new document is describing how to skip analyzing via a commit message.
=> Add "Skip Analyzing" document

docs/tools/java/pmd.md
- Add a options table.
- Add useful links to the official documentation.
=> Improve PMD Java document

docs/tools/php/codesniffer.md, docs/tools/php/phpmd.md
Also, this improves the PHP_CodeSniffer document.
For change details, see <https://github.com/sider/runners/blob/master/CHANGELOG.md#050>
=> Bump PHPMD and PHP_CodeSniffer

docs/tools/php/phpmd.md
- Add `custom_rule_path` option (see https://github.com/sider/runners/pull/323)
- Clean up code examples
- Add default values to the options table
=> Improve PHPMD document

docs/index.md, docs/tools/shellscript/shellcheck.md, website/sidebars.json
See also:
- https://www.shellcheck.net
- https://github.com/koalaman/shellcheck
=> Add ShellCheck document

docs/tools/css/stylelint.md, docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md, docs/tools/java/javasee.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/swift/swiftlint.md
This should be merged after Sider releases the update.
=> Update the descriptions about versions of tools and runtimes

docs/tools/ruby/rubocop.md
See https://github.com/sider/runners/issues/131
=> Add deprecation for older RuboCop

docs/tools/swift/swiftlint.md
- Add default values to the options table.
- Change down heading levels of each option.
=> Improve SwiftLint document

lefthook.yml, package.json, yarn.lock
- https://github.com/Arkweid/lefthook
- https://prettier.io
If you want to turn off temporarily, run `git commit --no-verify`.
=> Prettier markdown files on pre-commit

docs/index.md, docs/tools/cplusplus/cpplint.md, website/sidebars.json
See also:
- https://github.com/sider/runners/pull/417
- https://github.com/cpplint/cpplint
=> Support cpplint

docs/news/2019.md, website/sidebars.json, website/static/css/custom.css
We will have `news/2019.md`, `news/2020.md`, ...
=> Add news page

docs/tools/css/scss-lint.md, docs/tools/css/stylelint.md, docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md, docs/tools/java/checkstyle.md, docs/tools/java/javasee.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/javascript/tslint.md, docs/tools/kotlin/ktlint.md, docs/tools/others/goodcheck.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/python/flake8.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/querly.md, docs/tools/ruby/rails-bestpractices.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
Also, update the old or unclear descriptions.
See the following changes:
- https://github.com/sider/runners/blob/0.9.0/CHANGELOG.md
- https://github.com/sider/runners/blob/0.9.1/CHANGELOG.md
- https://github.com/sider/devon_rex/blob/2.8.0/CHANGELOG.md
=> Update tools and languages version

docs/getting-started/custom-configuration.md, docs/tools/cplusplus/cppcheck.md, docs/tools/cplusplus/cpplint.md, docs/tools/java/checkstyle.md, docs/tools/java/javasee.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/kotlin/ktlint.md, docs/tools/others/goodcheck.md, docs/tools/others/misspell.md, docs/tools/php/phpmd.md, docs/tools/python/flake8.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/querly.md, docs/tools/ruby/rails-bestpractices.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/shellscript/shellcheck.md
E.g. `array<string>` -> `string[]` (shorter)
=> Unify data types in `sider.yml`

docs/tools/cplusplus/cppcheck.md, docs/tools/cplusplus/cpplint.md, docs/tools/css/scss-lint.md, docs/tools/css/stylelint.md, docs/tools/java/checkstyle.md, docs/tools/java/javasee.md, docs/tools/java/pmd.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/kotlin/ktlint.md, docs/tools/others/goodcheck.md, docs/tools/others/misspell.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/python/flake8.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/querly.md, docs/tools/ruby/rails-bestpractices.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/shellscript/shellcheck.md, docs/tools/swift/swiftlint.md
=> Add `root_dir` option to each tool page

docs/tools/others/goodcheck.md
https://github.com/sider/runners/blob/0.10.0/CHANGELOG.md
https://github.com/sider/goodcheck/blob/v2.4.4/CHANGELOG.md
=> Bump Goodcheck

docs/tools/css/stylelint.md
https://github.com/sider/runners/blob/0.10.0/CHANGELOG.md
https://github.com/stylelint/stylelint/blob/12.0.0/CHANGELOG.md
=> Bump stylelint

goodcheck.yml
```
Invalid config: UnexpectedAttributeError at $.rules[0]: attribute=example
Expected to be positive_rule
0 expected to be rule
Expected to be rules
"rules" expected to be optional(rules)
$ expected to be config
Where:
positive_rule = {
"id": string,
"pattern": enum(array(pattern), pattern),
"message": string,
"justification": optional(enum(array(string), string)),
"glob": optional(glob),
"pass": optional(enum(array(string), string)),
"fail": optional(enum(array(string), string))
}
rule = enum(positive_rule, negative_rule, nopattern_rule, triggered_rule)
rules = array(rule)
config = {
"rules": optional(rules),
"import": optional(imports),
"exclude": optional(exclude)
}
```
=> Fix broken goodcheck.yml

docs/news/2019.md
See <https://github.com/sider/runners/blob/master/CHANGELOG.md#0100>
=> [News] Update tools on Nov 20, 2019

docs/news/2019.md, docs/tools/css/stylelint.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/ruby/rubocop.md
- https://github.com/sider/runners/blob/0.11.0/CHANGELOG.md
- https://github.com/sider/devon_rex/blob/2.10.0/CHANGELOG.md
=> [News] Update languages and tools on Nov 28, 2019

docs/news/2019.md, docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/others/goodcheck.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
See https://github.com/sider/runners/blob/master/CHANGELOG.md#0130
=> [News] Update languages and tools on Dec 17, 2019

docs/news/2019.md, docs/tools/ruby/rubocop.md
See https://github.com/sider/runners/blob/master/CHANGELOG.md#0140
=> [News] Update RuboCop and MeowCop for v0.78.0

docs/custom-rules/tips.md, docs/enterprise/administration.md, docs/enterprise/config.md, docs/enterprise/containers.md, docs/enterprise/database.md, docs/enterprise/github.md, docs/enterprise/healthcheck.md, docs/enterprise/http-proxy.md, docs/enterprise/outline.md, docs/enterprise/quickstart.md, docs/enterprise/releases/2018010801-201909.0.md, docs/enterprise/releases/201911.md, docs/enterprise/releases/202001.md, docs/enterprise/scaling.md, docs/enterprise/storage.md, docs/enterprise/updating.md, docs/troubleshooting.md, package.json, yarn.lock
This aims to make our review easier by adding some [remark-lint](https://github.com/remarkjs/remark-lint) rules.
I pick up carefully useful rules for us and do NOT add stylistic rules. (Because we have Prettier.)
See below for each rule details:
- List of core rules: https://github.com/remarkjs/remark-lint/blob/master/doc/rules.md
- List of external rules: https://github.com/remarkjs/remark-lint#list-of-external-rules
=> Check documents more strictly

docs/index.md, docs/tools/dockerfile/hadolint.md, website/sidebars.json
https://github.com/sider/runners/issues/581
=> Add hadolint to docs

docs/news/2020.md
=> Add news about Dockerfile (hadolint)

docs/tools/python/flake8.md
=> Add more details about Python 2 deprecation on Flake8 page

sider.yml
This fixes the Sider warning:
https://github.com/sider/sider-docs/pull/295#issuecomment-585137323
=> Add sider.yml for `npm_install: false`

docs/news/2020.md, docs/tools/css/stylelint.md, docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
https://github.com/sider/runners/releases/tag/0.19.0
https://github.com/sider/runners/blob/ed742205b66fac5d60995a8f79bbf462c7928f9c/CHANGELOG.md#0190
=> [News] Update languages and tools on Feb 13, 2020

docs/getting-started/custom-configuration.md
`ignore` and `branches` should be on top-level in `sider.yml`.
=> Clarify the position of the options in sider.yml

docs/enterprise/config.md
We decide not to support Loggly on Enterprise.
=> Goodbye Loggly

docs/index.md, docs/tools/go/golangci-lint.md, docs/tools/go/gometalinter.md, website/sidebars.json
See https://github.com/sider/runners/issues/484
=> Add GolangCI-Lint

docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md
https://github.com/sider/runners/issues/483
=> Add deprecated notice to go tools

docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md
See <https://github.com/sider/runners/pull/806>
=> Change deadline for Go tools

docs/news/2020.md, docs/tools/css/stylelint.md, docs/tools/go/golangci-lint.md, docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md, docs/tools/java/checkstyle.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/others/goodcheck.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
This is big news for new Runners version.
See <https://github.com/sider/runners/blob/master/CHANGELOG.md#0212>.
=> Add news for March 5, 2020

docs/index.md, docs/tools/markdown/remark-lint.md, website/sidebars.json
This change is related to sider/runners#672 and sider/runners#813.
=> Support remark-lint

docs/tools/php/codesniffer.md
See <https://github.com/sider/runners/blob/master/CHANGELOG.md#0190>
=> Fix PHP_CodeSniffer version

docs/tools/ruby/reek.md
Also, this change improves the document totally.
See https://github.com/sider/runners/pull/863
=> [Reek] Support new options

docs/tools/markdown/remark-lint.md
=> Publish remark-lint

docs/news/2020.md, docs/tools/cplusplus/cpplint.md, docs/tools/dockerfile/hadolint.md, docs/tools/go/golangci-lint.md, docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md, docs/tools/kotlin/detekt.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/swift/swiftlint.md
See also:
- https://github.com/sider/runners/blob/master/CHANGELOG.md#0220
- https://github.com/sider/devon_rex/blob/2.16.0/CHANGELOG.md#2160
=> News on March 25, 2020

docs/news/2019.md, docs/news/2020.md
This change aims to visually clarify the borders between each news item.
=> Insert horizontal border to split each news item

docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md
=> Extend the deadline for outdated Go tools

.remarkrc.yml, docs/enterprise/config.md, docs/enterprise/quickstart.md, docs/tools/go/gometalinter.md, docs/troubleshooting.md, package.json, yarn.lock
https://github.com/mapbox/remark-lint-link-text
=> Add `@mapbox/remark-lint-link-text` plugin and fix documents

docs/tools/javascript/jshint.md
- https://github.com/sider/runners/blob/master/images/jshint/sider_jshintrc
- https://github.com/sider/runners/blob/master/images/jshint/sider_jshintignore
=> [JSHint] Replace the default configuration code blocks with the links

docs/getting-started/setup.md
- Replace the outdated table of available tools with just a internal link.
- Fix wording and grammar mistakes.
- Remove implementation details.
=> Improve setup document

.remarkrc.yml, package.json, yarn.lock
Using <https://github.com/ybiquitous/remark-lint-code-block-syntax>
Fix #337
=> Check syntax in code blocks

docs/index.md, docs/tools/others/languagetool.md, website/sidebars.json
Related to https://github.com/sider/runners/pull/787
~~**NOTE: This PR is ready to review but not to be merged because this support is not released.**~~
We are ready to merge it!
=> Add LanguageTool

docs/tools/csharp/fxcop.md
=> [FxCop] roslyn-analyzers-runner provides a static code analysis without running build

docs/tools/php/codesniffer.md
- Add a brief summary about a tool.
=> [PHP_CodeSniffer] Improve document

docs/tools/javascript/coffeelint.md, sider.yml
- Add a brief summary about the tool.
=> [CoffeeLint] Improve document

lefthook.yml
We have run it on Sider instead.
=> Don't run remark-lint on pre-commit

docs/tools/cplusplus/cpplint.md
=> [cpplint] Drop the description column from the option table

docs/tools/kotlin/detekt.md
=> [detekt] Improve document

docs/tools/javascript/eslint.md
- Add a brief summary for the tool.
=> [ESLint] Improve document

docs/tools/csharp/fxcop.md
=> [FxCop] Drop the description column from the option table

docs/tools/go/golangci-lint.md
=> [GolangCI-Lint] Drop the description column from the option table

docs/tools/others/goodcheck.md
- Add a brief summary for the tool.
- Add each option's section.
=> [Goodcheck] Improve document

docs/tools/dockerfile/hadolint.md
=> [hadolint] Drop the description column from the option table

docs/tools/others/misspell.md
See <https://github.com/sider/runners/pull/1046>
=> [Misspell] Deprecate `targets` option

docs/tools/others/misspell.md
=> [Misspell] Improve document

docs/tools/java/javasee.md
=> [JavaSee] Improve document

docs/tools/javascript/jshint.md
=> [JSHint] Improve document

docs/tools/kotlin/ktlint.md
- Clarify some descriptions and headings.
=> [ktlint] Improve document

docs/tools/others/languagetool.md
=> [LanguageTool] Drop the description column from the option table

docs/tools/php/phinder.md
=> [Phinder] Improve document

docs/tools/php/phpmd.md
- Clarify each section's description.
=> [PHPMD] Improve document

docs/tools/java/pmd.md
- Clarify each section's description.
=> [PMD Java] Improve document

docs/tools/ruby/querly.md
- Clarify each section's description.
=> [Querly] Improve document

docs/tools/ruby/rails-bestpractices.md
- Add each option's description.
- Fix some options' default value.
- Replace the default configuration snippet with just a link.
=> [Rails Best Practices] Improve document

docs/tools/ruby/reek.md, sider.yml
=> [Reek] Improve document

docs/tools/markdown/remark-lint.md
=> [remark-lint] Improve document

docs/tools/ruby/rubocop.md
- Add "Getting Started" section.
- Clarify the each option's description.
=> [RuboCop] Improve document

docs/tools/ruby/brakeman.md
- Add "Getting Started" section.
=> [Brakeman] Improve document

docs/tools/css/scss-lint.md
- Add "Getting Started" section.
- Clarity each option's description.
=> [SCSS-Lint] Improve document

docs/tools/shellscript/shellcheck.md
=> [ShellCheck] Improve document

docs/tools/swift/swiftlint.md
=> [SwiftLint] Improve document

docs/tools/javascript/tslint.md
- Replace the default config snippet with a link to `sider/runners`.
=> [TSLint] Improve document

docs/tools/javascript/tyscan.md
=> [TyScan] Improve document

website/siteConfig.js
=> Add link to navigation header

docs/news/2020.md, docs/tools/css/stylelint.md, docs/tools/go/golangci-lint.md, docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md, docs/tools/javascript/jshint.md, docs/tools/kotlin/detekt.md, docs/tools/php/codesniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/python/flake8.md, docs/tools/ruby/querly.md, docs/tools/ruby/rubocop.md
This follows the release of Runners 0.24.0: https://github.com/sider/runners/blob/master/CHANGELOG.md#0240
=> [News] May 20, 2020

docs/tools/go/golangci-lint.md
=> [GolangCI-Lint] New website URL

docs/tools/cplusplus/cppcheck.md
Related on [sider/runners #1119](https://github.com/sider/runners/pull/1119)
=> Add document about addon option to cppcheck

docs/news/2020.md, docs/tools/cplusplus/cppcheck.md
See also https://github.com/sider/runners/blob/master/CHANGELOG.md#0250
=> [News] 2020-05-25

docs/news/2020.md
Add news for a new tool(Pylint)
=> Add news for Pylint

docs/tools/go/golangci-lint.md
=> Remove beta from GolangCI-Lint

docs/tools/cplusplus/cppcheck.md
See https://github.com/sider/runners/pull/1141
=> [Cppcheck] Note for a json file containing the configuration of addons

docs/news/2020.md, docs/tools/others/pmd-cpd.md
=> [News] 2020-06-08 PMD CPD support

docs/tools/cplusplus/cppcheck.md
Fix https://github.com/sider/runners/issues/1138
=> [Cppcheck] Support "Bug hunting"

docs/tools/cplusplus/cppcheck.md
=> Revert "[Cppcheck] Support "Bug hunting""

website/siteConfig.js
=> Add Enterprise page to header links

docs/tools/cplusplus/cppcheck.md
Reverts sider/sider-docs#441
Retry #439
**NOTE: This PR should be merged when a Runners new version will be released.**
=> Revert "Revert "[Cppcheck] Support "Bug hunting"""

docs/tools/others/pmd-cpd.md
=> [PMD CPD] Analyze multiple languages by default

docs/news/2020.md, docs/tools/cplusplus/cppcheck.md, docs/tools/cplusplus/cpplint.md, docs/tools/css/stylelint.md, docs/tools/dockerfile/hadolint.md, docs/tools/go/golangci-lint.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/kotlin/ktlint.md, docs/tools/markdown/remark-lint.md, docs/tools/php/code-sniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/python/flake8.md, docs/tools/python/pylint.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
- https://github.com/sider/runners/blob/master/CHANGELOG.md#0280
- https://github.com/sider/devon_rex/blob/master/CHANGELOG.md#2200
=> [News] 2020-06-18

docs/news/2020.md, docs/tools/ruby/rails-best-practices.md
See https://github.com/sider/runners/blob/master/CHANGELOG.md#0290
=> [News] 2020-06-25

docs/enterprise/config.md, docs/enterprise/installation.md
Our daily batch job requires an access to dockerd.
=> Add --volume in "Configuring cron jobs"

docs/enterprise/operation.md
Add a tip to remove old Docker images related to Sider Enterprise.
=> Add the section, "Remove old Docker images"

.remarkrc.yml, package.json, yarn.lock
https://github.com/sider/remark-preset-lint-sider
=> Use remark-preset-lint-sider

docs/custom-rules/introduction-to-custom-rules.md, docs/custom-rules/tips.md, docs/news/2019.md, docs/news/2020.md, goodcheck.yml
Also, this adds a Goodcheck rule about the use of `master` branch.
=> Fix remark-lint and Goodcheck issues

docs/custom-rules/goodcheck.md, docs/tools/others/goodcheck.md
I added a description of the `message` field.
=> Add additional message

goodcheck.yml
It is useful to run Goodcheck locally.
=> Add `exclude` to `goodcheck.yml`

docs/enterprise/operation.md, goodcheck.yml
See also https://github.com/sider/sider-docs/pull/466#discussion_r452585717
=> Add Goodcheck rule for internal links

docs/getting-started/custom-configuration.md, docs/index.md, docs/tools/cplusplus/clang-tidy.md, website/sidebars.json
Related to:
- https://github.com/sider/runners/issues/996
- https://github.com/sider/runners/issues/1066
- https://github.com/sider/runners/pull/1254
=> Support Clang-Tidy

docs/news/2020.md, docs/tools/cplusplus/clang-tidy.md, docs/tools/cplusplus/cpplint.md, docs/tools/css/stylelint.md, docs/tools/go/golangci-lint.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/kotlin/detekt.md, docs/tools/markdown/remark-lint.md, docs/tools/others/languagetool.md, docs/tools/others/misspell.md, docs/tools/others/pmd-cpd.md, docs/tools/php/phpmd.md, docs/tools/python/flake8.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/querly.md, docs/tools/ruby/rubocop.md
See the [changelog](https://github.com/sider/runners/blob/0.30.0/CHANGELOG.md).
=> [News] 2020-07-16

docs/news/2020.md, docs/tools/cplusplus/cpplint.md, docs/tools/go/golangci-lint.md, docs/tools/java/checkstyle.md, docs/tools/java/javasee.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/kotlin/detekt.md, docs/tools/kotlin/ktlint.md, docs/tools/markdown/remark-lint.md, docs/tools/others/languagetool.md, docs/tools/others/pmd-cpd.md, docs/tools/php/code-sniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/ruby/rubocop.md
https://github.com/sider/runners/blob/0.31.0/CHANGELOG.md
=> [News] 2020-07-28

docs/getting-started/custom-configuration.md, docs/tools/cplusplus/clang-tidy.md, docs/tools/cplusplus/cppcheck.md
Related to:
- https://github.com/sider/runners/issues/1280
=> [Cppcheck] Support the option `-I`

docs/getting-started/custom-configuration.md, docs/news/2020.md, docs/tools/css/stylelint.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/kotlin/detekt.md, docs/tools/kotlin/ktlint.md, docs/tools/markdown/remark-lint.md
See https://github.com/sider/runners/blob/0.32.0/CHANGELOG.md
=> [News] 2020-08-04

docs/getting-started/custom-configuration.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/kotlin/detekt.md, docs/tools/kotlin/ktlint.md
=> Fix `jvm_deps` type

docs/news/2020.md, docs/tools/cplusplus/cpplint.md, docs/tools/csharp/fxcop.md, docs/tools/go/golangci-lint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/kotlin/detekt.md, docs/tools/php/code-sniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/python/flake8.md, docs/tools/python/pylint.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
- https://github.com/sider/devon_rex/blob/2.25.0/CHANGELOG.md
- https://github.com/sider/runners/blob/0.33.0/CHANGELOG.md
=> [News] 2020-08-21

docs/tools/ruby/rubocop.md
=> [RuboCop] New website URL

docs/enterprise/github.md
Currently, Sider does not support self-signed certificates, so I want to clarify that.
=> Update github.md to ask users to use a trusted SSL cert

docs/tools/cplusplus/cppcheck.md
=> [Cppcheck] Run multiple threads with the `-j` option

docs/tools/swift/swiftlint.md
This PR contains below issues:
- Add support for params files for file path arguments #499
=> [SwiftLint] Add note for params files for `path` option

docs/news/2020.md, docs/tools/css/stylelint.md, docs/tools/go/golangci-lint.md, docs/tools/go/golint.md, docs/tools/go/gometalinter.md, docs/tools/go/govet.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/kotlin/detekt.md, docs/tools/kotlin/ktlint.md, docs/tools/others/goodcheck.md, docs/tools/others/pmd-cpd.md, docs/tools/php/code-sniffer.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/python/pylint.md, docs/tools/ruby/brakeman.md, docs/tools/swift/swiftlint.md
- https://github.com/sider/devon_rex/blob/2.26.1/CHANGELOG.md
- https://github.com/sider/runners/blob/0.35.0/CHANGELOG.md
=> [News] 2020-09-24

docs/enterprise/config.md, docs/enterprise/examples/single-node-with-docker-compose.md, docs/enterprise/releases/202009.md, docs/enterprise/releases/index.md, website/sidebars.json
We're planning to publish the next release in September 2020.
=> Enterprise Release - September 2020

docs/news/2020.md
- ~~no update https://github.com/sider/devon_rex/blob/2.26.1/CHANGELOG.md~~
- https://github.com/sider/runners/blob/0.36.0/CHANGELOG.md
=> [News] 2020-10-07

docs/advanced-settings/private-dependencies.md
The new document website is recommended on GitHub.
=> Update deloy key link on GitHub

docs/advanced-settings/private-dependencies.md
Addressing the review comments on PR #521
=> Follow-up of PR #521

docs/tools/php/code-sniffer.md
See https://github.com/sider/runners/pull/1650
- https://github.com/sider/runners/releases/tag/0.38.0 🎉
=> [PHPCS] Allow array for `extensions` and `ignore` options

docs/news/2020.md
=> Set missing date for the latest news

docs/troubleshooting.md
The maximum number of issues will be introduced soon.
This new section aims to help users address such a problem.
=> Add troubleshooting section for too many issues

docs/enterprise/releases/202008.md
We should have added a description of `bin/update_sider`.
=> Add a description of bin/update_sider

docs/news/2020.md, docs/tools/cplusplus/cppcheck.md, docs/tools/css/stylelint.md, docs/tools/dockerfile/hadolint.md, docs/tools/go/golangci-lint.md, docs/tools/java/checkstyle.md, docs/tools/java/javasee.md, docs/tools/java/pmd.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/javascript/tyscan.md, docs/tools/kotlin/detekt.md, docs/tools/kotlin/ktlint.md, docs/tools/markdown/remark-lint.md, docs/tools/others/goodcheck.md, docs/tools/others/languagetool.md, docs/tools/others/pmd-cpd.md, docs/tools/python/flake8.md, docs/tools/python/pylint.md, docs/tools/ruby/rubocop.md, docs/tools/swift/swiftlint.md
- https://github.com/sider/devon_rex/blob/2.28.0/CHANGELOG.md
- https://github.com/sider/runners/blob/0.39.0/CHANGELOG.md
=> [News] 2020-12-15

docs/tools/python/flake8.md
About a version specifier or VCS URL format. See <https://pip.pypa.io/en/stable/reference/pip_install/>.
=> [Flake8] Add more description about `plugins` option

docs/getting-started/custom-configuration.md
Add a link to the YAML spec for users unfamiliar with YAML: <https://yaml.org>
=> Make the description of sider.yml a bit kinder

docs/enterprise/examples/single-node-with-docker-compose.md, docs/enterprise/releases/202101.md
This release includes only bug fixes. See the changes for more details.
=> [release-202101.1] Enterprise release — January 2021

website/.eslintrc.yml
ESLint runs on Sider.
See also <https://github.com/yannickcr/eslint-plugin-react#configuration>.
=> Configure ESLint for React code

docs/tools/javascript/coffeelint.md
<https://coffeelint.github.io> is now available.
Also, <https://github.com/coffeelint/coffeelint> is the new repository.
=> Update CoffeeLint website

docs/tools/python/pylint.md
Follow the same format as Flake8. See #549.
=> Fix Pylint website URL

docs/tools/others/misspell.md
Misspell can detect typos in only English.
=> Fix supported language by Misspell

docs/getting-started/custom-configuration.md
This change aims to make the description more clear for users.
=> Improve `root_dir` option's description

website/static/css/custom.css
https://user-images.githubusercontent.com/473530/107645096-9fc36900-6cbb-11eb-849e-c992c84601e8.mov
See also:
- https://css-tricks.com/almanac/properties/s/scroll-behavior
- https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
=> Set CSS `scroll-behavior: smooth`

docs/getting-started/recommended-rules.md, docs/news/2021.md, docs/tools/java/checkstyle.md, docs/tools/javascript/coffeelint.md, docs/tools/javascript/eslint.md, docs/tools/python/pylint.md, docs/tools/ruby/rubocop.md
See also <https://github.com/sider/runners/releases/tag/0.43.0>.
This change includes a part of #557. (/cc @sleeeto )
=> [News] 2021-02-17

docs/custom-rules/goodcheck.md, docs/custom-rules/tips.md, docs/getting-started/custom-configuration.md, docs/tools/cplusplus/cpplint.md, docs/tools/css/stylelint.md, docs/tools/go/golangci-lint.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/javascript/tslint.md, docs/tools/php/phinder.md, docs/tools/php/phpmd.md, docs/tools/python/flake8.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/querly.md, docs/tools/ruby/rails-best-practices.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/ruby/slim-lint.md, docs/tools/shellscript/shellcheck.md
```console
$ goodcheck check docs -R sider.sider-docs.master_branch
91 files inspected, no issues detected
```
=> Avoid `master` word

docs/news/2021.md, docs/tools/css/stylelint.md, docs/tools/go/golangci-lint.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/others/pmd-cpd.md, docs/tools/python/pylint.md
See <https://github.com/sider/runners/blob/master/CHANGELOG.md#unreleased>
=> [News] 2021-03-02

docs/tools/go/golangci-lint.md
See https://github.com/sider/runners/pull/2103
=> [GolangCI-Lint] Fix default value of `target`option

docs/getting-started/recommended-rules.md, docs/tools/java/checkstyle.md, docs/tools/php/code-sniffer.md, docs/tools/python/flake8.md
Enable Sider's recommended ruleset of checkstyle and flake8 and phpcs.
=> Enable Sider's recommended ruleset of checkstyle and flake8 and phpcs.

docs/custom-rules/goodcheck.md, docs/getting-started/custom-configuration.md, docs/tools/java/checkstyle.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/haml-lint.md, docs/tools/ruby/querly.md, docs/tools/ruby/rails-best-practices.md, docs/tools/ruby/reek.md, docs/tools/ruby/rubocop.md, docs/tools/ruby/slim-lint.md, docs/tools/shellscript/shellcheck.md
The `hash` word is Ruby-specific. And, it is confusing.
=> Use `map` instead of `hash`

docs/tools/javascript/tslint.md
`tslint-to-eslint-config` is a migration tool from TSLint to ESLint.
https://www.npmjs.com/package/tslint-to-eslint-config
=> [TSLint] Add `tslint-to-eslint-config`

docs/tools/javascript/eslint.md
This change aims to make the "Getting Started" section about ESLint easier to read by shorter descriptions.
The ESLint documentation is now accurate and comprehensive, so I think it good enough that our documentation is simpler.
=> [ESLint] Update "Getting Started"

docs/tools/kotlin/ktlint.md
These options were removed and unused.
=> [ktlint] Remove outdated options

docs/tools/javascript/eslint.md
=> [ESLint] minor fix for link

docs/getting-started/custom-configuration.md, docs/news/2021.md, docs/tools/python/flake8.md
See https://github.com/sider/runners/releases/tag/0.47.0
- Support `linter.<id>.dependencies` for Python
=> [News] 2021-04-07

docs/getting-started/recommended-rules.md, docs/news/2021.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/ruby/rubocop.md
Add Sider's recommended ruleset documents of ESLint, RuboCop, PMD.
- Reference
- https://github.com/sider/sideci/issues/9963
- https://github.com/sider/sideci/issues/9964
- https://github.com/sider/sideci/issues/10434
=> Added the recommended ruleset of ESlint, RuboCop, PMD

docs/enterprise/config.md, docs/enterprise/examples/single-node-with-docker-compose.md, docs/enterprise/installation.md, docs/enterprise/minio.md, docs/enterprise/operation.md, docs/enterprise/releases/202001.md, docs/enterprise/releases/202002.md, docs/enterprise/releases/202004.md, docs/enterprise/releases/202005.md, docs/enterprise/releases/202006.md, docs/enterprise/releases/202007.md, docs/enterprise/updating.md
Use consistent formats between the documents.
=> Improve Enterprise documents

docs/enterprise/examples/single-node-with-docker-compose.md, docs/enterprise/releases/202106.md, docs/enterprise/releases/index.md, website/sidebars.json
See https://github.com/sider/sideci/issues/11225
=> Enterprise release — June 2021

docs/index.md, docs/news/2021.md, docs/tools/cplusplus/cpplint.md, docs/tools/dockerfile/hadolint.md, docs/tools/go/golangci-lint.md, docs/tools/java/checkstyle.md, docs/tools/java/pmd.md, docs/tools/javascript/eslint.md, docs/tools/javascript/jshint.md, docs/tools/kotlin/detekt.md, docs/tools/others/goodcheck.md, docs/tools/others/pmd-cpd.md, docs/tools/others/secret-scan.md, docs/tools/python/pylint.md, docs/tools/ruby/brakeman.md, docs/tools/ruby/rubocop.md, docs/tools/ruby/slim-lint.md, website/sidebars.json
This adds the **Secret Scan** page.
https://github.com/sider/runners/blob/0.50.0/CHANGELOG.md
=> [News] 2021-06-16

docs/advanced-settings/private-dependencies.md
- Add a link to the `dependencies` option of `sider.yml`
- Clarify some existing descriptions.
=> Improve "Private Dependencies" page

README.md, docs/custom-rules/goodcheck.md
https://sider.review/gh/repos/142577083/branches/master/commits/329e80587d7d5b8356867c2dd068c13bb7c33ec3?tools%5B%5D=remark_lint&rules%5B%5D=no-dead-urls#issues
=> Fix dead links

docs/getting-started/recommended-rules.md, docs/news/2021.md, docs/tools/cplusplus/cppcheck.md, docs/tools/php/phpmd.md
https://github.com/sider/runners/blob/0.52.0/CHANGELOG.md
=> [News] 2021-07-13
